# Generated by Django 5.2.1 on 2025-11-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscription_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('Tricycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='app.tricycle')),
            ],
        ),
    ]
