# Generated by Django 5.2.1 on 2026-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_payment_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lien',
            field=models.URLField(blank=True, verbose_name='Lien Google Maps'),
        ),
    ]
