# Generated by Django 5.2.1 on 2026-02-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_payment_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
