# Generated by Django 5.2.1 on 2026-03-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_payment_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='frequency',
            field=models.CharField(choices=[('1000', '2000'), ('3000', '1500'), ('2500', '3000'), ('3500', '5000'), ('4000', '4500'), ('10000', '15000')], max_length=20),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscription')),
            ],
        ),
    ]
