# Generated by Django 5.2.1 on 2026-03-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_subscriptionplan_frequency_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='number',
            field=models.IntegerField(),
        ),
    ]
