# Generated by Django 5.2.1 on 2026-03-13 19:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_bonus_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasCylinder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='cylinders_qr/', verbose_name='QR Code')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('with_customer', 'Chez le client'), ('in_transit', 'En transit'), ('returned', 'Retournée'), ('damaged', 'Endommagée'), ('lost', 'Perdue')], default='available', max_length=20)),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Dernière maintenance')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Prochaine maintenance')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'achat")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cylinders', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire actuel')),
            ],
            options={
                'verbose_name': 'Bouteille de gaz',
                'verbose_name_plural': 'Bouteilles de gaz',
            },
        ),
        migrations.CreateModel(
            name='GasOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° de commande')),
                ('delivery_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('scheduled', 'Programmée')], default='standard', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Date programmée')),
                ('scheduled_time_slot', models.CharField(blank=True, max_length=50, verbose_name='Créneau horaire')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('assigned', 'Assignée à un livreur'), ('in_transit', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('partial', 'Partiellement payée'), ('failed', 'Échouée'), ('refunded', 'Remboursée')], default='pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('confirmation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('preparation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de préparation')),
                ('pickup_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'enlèvement")),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure estimée de livraison')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sous-total')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de livraison')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxes')),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total consigne')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Méthode de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gas_orders', to='app.address', verbose_name='Adresse de livraison')),
                ('assigned_collector', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'collecteur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_gas_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Livreur assigné')),
                ('assigned_tricycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_deliveries', to='app.tricycle', verbose_name='Tricycle assigné')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gas_orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_orders', to='app.payment')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_orders', to='app.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Commande de gaz',
                'verbose_name_plural': 'Commandes de gaz',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='GasExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exchange_type', models.CharField(choices=[('return_only', 'Retour uniquement'), ('exchange', 'Échange standard'), ('purchase_new', 'Achat neuf sans retour')], default='exchange', max_length=20)),
                ('returned_condition_notes', models.TextField(blank=True, verbose_name='État des bouteilles retournées')),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Différence de prix')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_cylinders', models.ManyToManyField(related_name='exchanges_as_new', to='app.gascylinder', verbose_name='Bouteilles neuves fournies')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('returned_cylinders', models.ManyToManyField(related_name='exchanges_as_return', to='app.gascylinder', verbose_name='Bouteilles retournées')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='app.gasorder', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Échange de bouteilles',
                'verbose_name_plural': 'Échanges de bouteilles',
            },
        ),
        migrations.CreateModel(
            name='GasDeliveryTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('assigned', 'Assignée à un livreur'), ('in_transit', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('failed', 'Échouée')], max_length=20, verbose_name='Statut')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy', models.CharField(blank=True, max_length=50, verbose_name='Précision')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Arrivée estimée')),
                ('distance_remaining', models.FloatField(blank=True, null=True, verbose_name='Distance restante (km)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/%Y/%m/%d/', verbose_name='Photo de livraison')),
                ('recipient_signature', models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m/%d/', verbose_name='Signature du destinataire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='app.gasorder', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Suivi de livraison',
                'verbose_name_plural': 'Suivis de livraison',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GasProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('gaz_type', models.CharField(choices=[('butane', 'Gaz Butane'), ('propane', 'Gaz Propane'), ('naturel', 'Gaz Naturel'), ('industriel', 'Gaz Industriel')], max_length=20, verbose_name='Type de gaz')),
                ('size_kg', models.IntegerField(choices=[(3, '3 kg'), (6, '6 kg'), (12, '12 kg'), (25, '25 kg'), (35, '35 kg'), (50, '50 kg')], verbose_name='Taille (kg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('deposit_price', models.DecimalField(decimal_places=2, help_text='Prix de la bouteille consignée', max_digits=10, verbose_name='Prix de consigne')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gaz_products/', verbose_name='Image')),
                ('stock_available', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit gaz',
                'verbose_name_plural': 'Produits gaz',
                'ordering': ['gaz_type', 'size_kg'],
                'unique_together': {('gaz_type', 'size_kg')},
            },
        ),
        migrations.CreateModel(
            name='GasOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('unit_deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consigne unitaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_cylinders', models.ManyToManyField(blank=True, related_name='orders', to='app.gascylinder', verbose_name='Bouteilles assignées')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.gasorder', verbose_name='Commande')),
                ('returned_cylinders', models.ManyToManyField(blank=True, related_name='returned_in_orders', to='app.gascylinder', verbose_name='Bouteilles retournées')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.gasproduct', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article commandé',
                'verbose_name_plural': 'Articles commandés',
            },
        ),
        migrations.CreateModel(
            name='GasInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('warehouse', 'Entrepôt'), ('tricycle', 'Tricycle'), ('shop', 'Boutique')], max_length=20)),
                ('warehouse_name', models.CharField(blank=True, max_length=100, verbose_name="Nom de l'entrepôt")),
                ('quantity_available', models.PositiveIntegerField(default=0, verbose_name='Quantité disponible')),
                ('quantity_reserved', models.PositiveIntegerField(default=0, verbose_name='Quantité réservée')),
                ('quantity_damaged', models.PositiveIntegerField(default=0, verbose_name='Quantité endommagée')),
                ('minimum_threshold', models.PositiveIntegerField(default=5, verbose_name='Seuil minimum')),
                ('maximum_capacity', models.PositiveIntegerField(default=100, verbose_name='Capacité maximale')),
                ('last_restock_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernier réapprovisionnement')),
                ('last_count_date', models.DateTimeField(auto_now=True, verbose_name='Dernier inventaire')),
                ('tricycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gas_inventory', to='app.tricycle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='app.gasproduct')),
            ],
            options={
                'verbose_name': 'Inventaire gaz',
                'verbose_name_plural': 'Inventaires gaz',
            },
        ),
        migrations.AddField(
            model_name='gascylinder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cylinders', to='app.gasproduct', verbose_name='Produit'),
        ),
        migrations.CreateModel(
            name='GasPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la promotion')),
                ('description', models.TextField(verbose_name='Description')),
                ('promotion_type', models.CharField(choices=[('percentage', 'Pourcentage de réduction'), ('fixed', 'Montant fixe'), ('bundle', 'Pack multiple'), ('free_delivery', 'Livraison gratuite')], max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur de réduction')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de réduction')),
                ('minimum_purchase', models.PositiveIntegerField(default=1, verbose_name='Achat minimum')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code promo')),
                ('usage_limit', models.PositiveIntegerField(default=0, verbose_name="Limite d'utilisation")),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='promotions', to='app.gasproduct')),
                ('applicable_zones', models.ManyToManyField(blank=True, related_name='promotions', to='app.zone')),
            ],
            options={
                'verbose_name': 'Promotion gaz',
                'verbose_name_plural': 'Promotions gaz',
            },
        ),
        migrations.CreateModel(
            name='GasRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product_quality', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('delivery_speed', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('collector_behavior', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gas_ratings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_ratings', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='app.gasorder')),
            ],
            options={
                'verbose_name': 'Évaluation gaz',
                'verbose_name_plural': 'Évaluations gaz',
            },
        ),
        migrations.AddIndex(
            model_name='gasorder',
            index=models.Index(fields=['order_number', 'status'], name='app_gasorde_order_n_753c96_idx'),
        ),
        migrations.AddIndex(
            model_name='gasorder',
            index=models.Index(fields=['customer', 'order_date'], name='app_gasorde_custome_ac6591_idx'),
        ),
        migrations.AddIndex(
            model_name='gasorder',
            index=models.Index(fields=['assigned_collector', 'status'], name='app_gasorde_assigne_e94e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='gasorder',
            index=models.Index(fields=['scheduled_date', 'status'], name='app_gasorde_schedul_01fed2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gasinventory',
            unique_together={('product', 'location_type', 'tricycle')},
        ),
        migrations.AddIndex(
            model_name='gascylinder',
            index=models.Index(fields=['serial_number', 'status'], name='app_gascyli_serial__242e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='gascylinder',
            index=models.Index(fields=['product', 'status'], name='app_gascyli_product_aa9456_idx'),
        ),
    ]
