# Generated by Django 5.2.1 on 2026-03-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_gascylinder_gasorder_gasexchange_gasdeliverytracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasorder',
            name='scheduled_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date programmée'),
        ),
    ]
