# Generated by Django 5.2.1 on 2026-03-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_gasorder_scheduled_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gasproduct',
            unique_together=set(),
        ),
    ]
